name: Model Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision
    
    - name: Cache MNIST data
      uses: actions/cache@v4
      with:
        path: data
        key: mnist-data
    
    - name: Run tests
      run: python test_model.py
    
    - name: Upload model artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mnist-model
        path: mnist_model.pth
        retention-days: 90
    
    - name: Report results
      run: |
        echo "Model test results:"
        echo "- Parameters: $(python -c 'from mnist_model import LightMNIST, count_parameters; print(count_parameters(LightMNIST()))')"
        echo "- Accuracy: See test output above"