name: Model Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision matplotlib pytest numpy psutil
    
    - name: Cache MNIST data
      uses: actions/cache@v4
      with:
        path: data
        key: mnist-data
    
    - name: Generate augmentation samples
      run: |
        mkdir -p data/augmented_samples
        python utils/visualize_augmentation.py
        ls -la data/augmented_samples/
    
    - name: Run tests
      run: |
        python -m pytest test_model.py -v
    
    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: |
          mnist_model.pth
          data/augmented_samples/*.png
        retention-days: 90
    
    - name: Report results
      run: |
        echo "Model test results:"
        echo "- Parameters: $(python -c 'from mnist_model import LightMNIST, count_parameters; print(count_parameters(LightMNIST()))')"
        echo "- Accuracy: See test output above"
        echo "- Generated images: $(ls data/augmented_samples/*.png | wc -l) files"